---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
  environment:
    - NODE_ENV: production
    - ENVIRONMENT: production
    - TYPEORM_CONNECTION: postgres
    - TYPEORM_ENTITIES: ./src/modules/domain/**/*.entity.ts
    - TYPEORM_HOST: postgres.cyan0kujbxdm.us-east-1.rds.amazonaws.com
    - TYPEORM_PORT: 5432
    - TYPEORM_USERNAME: postgres
    - TYPEORM_PASSWORD: postgres
    - TYPEORM_DATABASE: postgres
    - TYPEORM_MIGRATIONS: ./src/migrations/*.ts
    - TYPEORM_MIGRATIONS_DIR: ./src/migrations

  roles:
    - deploy
