---
- name: "show remote environment"
  shell: env

- name: "copy backend binaries"
  become: yes
  synchronize:
    src: ../../backend/dist
    dest: /home/ubuntu/uda_app
    recursive: true

- name: "copy node_modules"
  become: yes
  synchronize:
    src: ../../backend/node_modules
    dest: /home/ubuntu/uda_app
    recursive: true

- name: "delete anything that might already be running"
  become: true
  command: pm2 delete all
  ignore_errors: true
- name: 'update and upgrade packages.'
  become: yes
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400
- name: remove unneeded dependencies
  become: yes
  apt:
    autoremove: yes
- name: "install npm"
  become: yes
  apt:
    name: 'npm'
    state: latest
    update_cache: yes
- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    state: latest
    production: yes

- name: "install n"
  become: yes
  npm:
    name: n
    global: yes
    production: yes

- name: "install nodejs 13.8.0"
  become: yes
  shell: n 13.8.0
      
- name: "extract artifact"
  become: yes
  unarchive:
    src: files/artifact.tar.gz
    dest: .

- name: "start app"
  become: yes
  shell: |
    pm2 stop all
    pm2 start npm -- start
  args:
    chdir: /home/ubuntu/uda_app/dist
  environment:
    - NODE_ENV: production
    - ENVIRONMENT: production
    - TYPEORM_CONNECTION: postgres
    - TYPEORM_ENTITIES: ./src/modules/domain/**/*.entity.ts
    - TYPEORM_HOST: postgres.cyan0kujbxdm.us-east-1.rds.amazonaws.com
    - TYPEORM_PORT: 5432
    - TYPEORM_USERNAME: postgres
    - TYPEORM_PASSWORD: postgres
    - TYPEORM_DATABASE: postgres
    - TYPEORM_MIGRATIONS: ./src/migrations/*.ts
    - TYPEORM_MIGRATIONS_DIR: ./src/migrations